name: outside_pr

on:
  pull_request:
    branches: [ main ]
    types: [ labeled ]
    paths-ignore:
    - 'docs/**'
    - 'README.md'

jobs:
  build:
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Get all git tags
        run: git fetch --prune --unshallow --tags
      - name: Setup Go for Building
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.2'
      - name: Setup Ginkgo Test Framework
        run: go get -u github.com/onsi/ginkgo/v2/ginkgo
      - name: Cache Tools
        uses: actions/cache@v3.0.1
        with:
          path: ${{ github.workspace }}/tools
          key: ${{ runner.os }}-tools
      - name: Install Tools
        run: make tools-install
      - name: Add Tools to PATH
        run: |
          echo "`pwd`/output/bin" >> $GITHUB_PATH
      - name: lint Epinio
        run: make lint
      - name: Run unit tests
        run: make test
      - name: Acceptance tests
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          export GINKGO_NODES=8
          make acceptance-cluster-delete
          make acceptance-cluster-setup
          export KUBECONFIG=$PWD/tmp/acceptance-kubeconfig
          make test-acceptance
